name: deploy-gh-page

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone public repo via HTTPS
      uses: chihqiang/checkout-action@main
      with:
        repository: chihqiang/blog.hexo
        ref: main
        token: ${{ secrets.GH_TOKEN }}
        
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        
    - name: hexo build 
      run: make build
      
    - name: Publish to gh-pages branch
      uses: chihqiang/gh-pages-action@main
      with:
        publish_dir: public
        target_branch: gh-pages
        token: ${{ secrets.GH_TOKEN }}
    
    - name: Clean up tags, releases, workflow runs, branches & caches
      uses: chihqiang/gh-cleanup-action@main
      with:
        token: ${{ secrets.GH_TOKEN }}
        keep_tag: 1
        keep_release: 1
        keep_run: 1
        keep_branch: 2
        keep_action_cache: 1
        dry_run: false
